name: CI

on:
  push:
    branches:
      - main
      - tests_CI_CD
  pull_request:
    branches:
      - main
      - tests_CI_CD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
